### ISSUE TITLE
Add to Dash

### ISSUE THREAD

**Issue by MaxHasADHD** [joemasilotti/XCTest-Documentation#1]
Could you add this to Dash? :) https://github.com/Kapeli/Dash-User-Contributions#contribute-a-new-docset

**Comment by joemasilotti** [comment]
Great idea! I just submitted a PR.

https://github.com/Kapeli/Dash-User-Contributions/pull/525

**Comment by joemasilotti** [comment]
And it's been merged! Closing this, thanks again for the idea.
